version: "3.7"

services:
  app:
    build: currency_converter/
    ports:
      - "8080:8080"
    links:
      - redis
    restart: always

  redis:
    image: redis:6
    volumes:
      - ./volumnes/redis:/data
    restart: always
    ports:
      - "6379:6379"
